### ISSUE TITLE
您好，你博客中图片地址全部失效，能够更新一下吗？

### ISSUE THREAD

**Issue by stevve** [sunweiguo/notebook2.0#1]

**Comment by sunweiguo** [comment]
感谢关注博客~，正在处理图片问题。。。原因是我的域名备案出了问题。。。

**Comment by yixinWang2018** [comment]
博主，点开你的另外io的博客好像博客也失效了。。

**Comment by sunweiguo** [comment]
> 博主，点开你的另外io的博客好像博客也失效了。。

嗯嗯，因为共用的一个，https://sunweiguo.github.io这个展现效果好一点。。并且后来的更新都在io这边，没有维护这个仓库。
图片问题只能等待慢慢处理了，，比较繁琐。自己也很愁，想看自己的博客都不好看😂

**Comment by yixinWang2018** [comment]
hh 很喜欢你的博客，期待早日修复好！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fossi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 晚上10:20
收件人:&nbsp;"sunweiguo/notebook2.0"<notebook2.0@noreply.github.com&gt;;
抄送:&nbsp;"Yixin Wang"<864588014@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sunweiguo/notebook2.0] 您好，你博客中图片地址全部失效，能够更新一下吗？ (#1)



 
博主，点开你的另外io的博客好像博客也失效了。。
  
嗯嗯，因为共用的一个，https://sunweiguo.github.io这个展现效果好一点。。并且后来的更新都在io这边，没有维护这个仓库。
 图片问题只能等待慢慢处理了，，比较繁琐。自己也很愁，想看自己的博客都不好看😂

**Comment by sunweiguo** [comment]
> hh 很喜欢你的博客，期待早日修复好！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"fossi"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月9日(星期一) 晚上10:20 收件人:&nbsp;"sunweiguo/notebook2.0"<notebook2.0@noreply.github.com&gt;; 抄送:&nbsp;"Yixin Wang"<864588014@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [sunweiguo/notebook2.0] 您好，你博客中图片地址全部失效，能够更新一下吗？ (#1) 博主，点开你的另外io的博客好像博客也失效了。。 嗯嗯，因为共用的一个，[https://sunweiguo.github.io这个展现效果好一点。。并且后来的更新都在io这边，没有维护这个仓库。](https://sunweiguo.github.io%E8%BF%99%E4%B8%AA%E5%B1%95%E7%8E%B0%E6%95%88%E6%9E%9C%E5%A5%BD%E4%B8%80%E7%82%B9%E3%80%82%E3%80%82%E5%B9%B6%E4%B8%94%E5%90%8E%E6%9D%A5%E7%9A%84%E6%9B%B4%E6%96%B0%E9%83%BD%E5%9C%A8io%E8%BF%99%E8%BE%B9%EF%BC%8C%E6%B2%A1%E6%9C%89%E7%BB%B4%E6%8A%A4%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E3%80%82) 图片问题只能等待慢慢处理了，，比较繁琐。自己也很愁，想看自己的博客都不好看😂 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

快了，刚才工信部流程走完了，现在走腾讯云备案流程，估摸这几天就好了，到时候我会在这里再说下~

**Comment by sunweiguo** [comment]
图片恢复正常了啦 ~~后续我会对这个博客的内容重新修整一遍，再加点料
